### PR TITLE
Fix missing search route

### PR DESCRIPTION
**Pull request by wmitsuda**
that should fix https://github.com/otterscan/otterscan/issues/2286

### CODE REVIEW

**Comment by wmitsuda** [comment]
actually, this one fixes the route, but not the refreshing loop, for some reason earlier today it was not happening anymore, but now it is...

**Review by sealer3 — CHANGES_REQUESTED** [review]
Thanks for fixing the route. This PR doesn't fix the infinite config reloading issue however, so I don't think it should close #2286 when merged. Could you check whether the infinite config reloading happens on your end? I've tried multiple browsers, and they exhibit the same behavior.

**Comment by wmitsuda** [comment]
yes, it doesn't fix the reloading, will rework the PR :)

**Comment by wmitsuda** [comment]
The latest commit should fix the case when it gets an error because it is updating a parent state, probably because of navigate() function in-sync with the UI thread.

However I think the infinite loop is not related, I tried to put a log inside the `evaluateScan` function and for the case when the reload loop still happens, the log happens as well.

So what I believe is happening in this case is:

- camera does not get closed and scanning (can confirm that from the "scan" log being continously emited)
- the event keeps being emited, but with the already scanned code
- the redir keeps being executed

that explains the infinite config reloading, because it is like the same QR code being infinitely being scanned and redirected.

I'd recommend we merge this PR as is, as all fixes I did here are valid regardless of the camera problem and we continue discussing the camera issue in https://github.com/otterscan/otterscan/issues/2320

**Review by sealer3 — APPROVED** [review]
Okay, I think we can merge this. The infinite config reloading bug still needs to be addressed, but I don't think it's because of the camera.

There are other outstanding problems (they occur on the develop branch too): when you open the QR scanner, you see the ETH node checking page again briefly. Also, when I issue console logs in the QR scanner, they appear in groups of two. So it seems that all the components are duplicated somehow.

Also, #2259 results in the same infinite config reloading behavior, probably also due to routing.

**Comment by wmitsuda** [comment]
I think #2259 can be solved by a similar solution to this one, will send a PR soon.

re: duplicate log, I'm almost sure it is bc: https://stackoverflow.com/questions/72489140/react-18-strict-mode-causing-component-to-render-twice

you can mitigate the double log confusion by installing react devtools extension: https://www.frontendundefined.com/posts/react-issues/double-console-react-18/

> when you open the QR scanner, you see the ETH node checking page again briefly.

hm, let me try to see this one

**Comment by sealer3** [comment]
You're right, half the logs were in a lighter color. I didn't understand why the `scan` log was appearing in groups of two, but maybe it's for the same reason.

**Pull request merged**
