### PR TITLE
Add token price resolvers

### LINKED ISSUE #1879: Price feed support on Optimism
We currently only display USD values on mainnet duue to Chainlink only supporting the FeedRegistry contract on mainnet.

That's very annoying, but I really don't want us to hardcode feed addresses on our side. But it is also annoying not having USD info on other chains.

So, I'd like to propose a midterm solution which we can test on Optimism, which is:

1 - Hardcode the ETH/USD price oracle for that chain: https://docs.chain.link/data-feeds/price-feeds/addresses?network=optimism&page=4

2 - Use Uniswap V2 (or V3?) factory `getPair()` to discover/derive other token LPs <-> ETH, and use it to estimate the spot price.

3 - Apply this oracle solution on chainid 10 (optimism mainnet) instead of the feed registry to display USD values when applicable.

### PR DESCRIPTION
**Pull request by sealer3**
Adds support for using UniswapV2 and UniswapV3 spot prices for price estimations, enabling tokens without Chainlink data feeds to have their price estimates shown.

In addition, this change allows the native token USD price data feed contract address to be specified in the config.

Note that the UniswapV3 "is there enough liquidity to trust this price" check is subject to being incorrect if there is a substantial amount of out-of-range liquidity and little or no liquidity in the active range, e.g. if the true price of the token is higher than all active liquidity positions. If it's easy to calculate how much liquidity is on either side of the current token price without having to make too many extra calls, that could be a future improvement.

Other future improvement: Users may wish to know the source of the price data. We may also wish to change the background color of the price estimate based on the source of the information.

Closes #1879.

### CODE REVIEW

**Comment by wmitsuda** [comment]
I think you forgot to embed the configuration for chainId == 10 (op-mainnet), which was the main driver of this issue :)

**Comment by wmitsuda** [comment]
in fact, I was not thinking about adding alternative resolvers on mainnet for now in order to not complicate things, but you rightfully guessed where we were aiming to :)

but yes, regarding L1 mainnet, one of the issues created by having more than 1 resolver is trust and transparency regarding the source. I was thinking about having difference colors for different sources, maybe we change the chainlink to use a "chainlink blue logo"-color and uni use a "uniswap-pink"-color?

**Comment by sealer3** [comment]
Uniswap price sources have a fuschia color. I decided to keep the neutral gray color for Chainlink price sources since I didn't want the price information to become too much of a distraction.
image

For comparison, it would look like this with a blue color:
image


Optimism now has its price oracle information embedded without the need for a custom configuration.

**Comment by wmitsuda** [comment]
> Uniswap price sources have a fuschia color. I decided to keep the neutral gray color for Chainlink price sources since I didn't want the price information to become too much of a distraction. 

ok, let's keep the gray considering Chainlink is the "canonical" oracle. but open to revisit it.

**Review by wmitsuda — APPROVED** [review]
finally was able to test it on mainnet, that's a great feature!

**Pull request merged**
