### PR TITLE
Add blob details to transaction page

### LINKED ISSUE #1756: Add stateRoot and receiptsRoot to block pages
These represent the merkle roots of the state and receipt tries for the block. These are planned to be included in the ethers Block object in its next minor release.

### PR DESCRIPTION
**Pull request by sealer3**
Related: #1727 

Adds blob information to the transaction page and includes the blob fee in the transaction fee section. Note that the blob fee is not yet included in the Transaction Fee column yet for the address and block pages.

image

Closes #1756

### CODE REVIEW

**Comment by sealer3** [comment]
I've expanded this PR to include some Dencun details on the Block page (plus Receipts Root):
image

In a future issue we can make the parent beacon block root a link to a beacon block. This is achievable using the same [/eth/v2/beacon/blocks/{block_id}](https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockV2) endpoint we already use for slots.

**Comment by wmitsuda** [comment]
> Related: #1727
> 
> Adds blob information to the transaction page and includes the blob fee in the transaction fee section. Note that the blob fee is not yet included in the Transaction Fee column yet for the address and block pages.
> 
> image

I liked it. I'd like some vertical space between the blob hashes (I think space-y-1 works) to give it some breath, right now the section looks "a little busy".

**Comment by sealer3** [comment]
Done:
image

**Review by wmitsuda — APPROVED** [review]
good!

**Pull request merged**
