### PR TITLE
Split tuple inputs in read contract interface

### PR DESCRIPTION
**Pull request by sealer3**
Creates a new component that handles a list of parameters. This design makes recursive tuple input possible. Partially addresses #1192 since only base types of "tuple" are supported - arrays will require an interface for adding and removing elements.

### CODE REVIEW

**Comment by wmitsuda** [comment]
I think this is a good opportunity to make some storybook stories for these components before we have too much of them to test.

Could you write some stories for the tuple case and also for the individual ones so we can easily test/inspect them in the storybook UI?

I think the component to be test could be the label + input box below it. Then we could easily see if tuples, arrays, etc, render the subtypes correctly.

**Comment by sealer3** [comment]
I've added stories for this new component. Note that the tuple types will not be formatted correctly in the stories due to this bug in ethers: https://github.com/ethers-io/ethers.js/issues/4329

The JSON contract ABI returned from Sourcify is immune to this somehow.

**Comment by wmitsuda** [comment]
oh, fuck... anyway, rebase again plz? I think it got conflicted after I merged the prettier PR.

**Comment by sealer3** [comment]
Done

**Comment by wmitsuda** [comment]
note to self: a good contract to test it on mainnet is: 0x1111111254EEB25477B68fb85Ed929f73A960582

**Comment by wmitsuda** [comment]
I'd like to make one last UI adjustment given the recent improvement to color param names/types: see in the screenshot below, in this case, let's replace the "tuple....." with a similar colored string "tuple(...) order" (replacing the giant parameter list with an ellipsis because the params are now described individually).

image

**Comment by sealer3** [comment]
How it looks now:

image

**Comment by wmitsuda** [comment]
it looks good. there is still something missing linking the tuple to the inner params, maybe a different color or extra UI element, I'll think about that in another issue.

**Pull request merged**
