### PR TITLE
Add token equivalence map to token price oracle

### LINKED ISSUE #605: Wrapped Ether price in token transfers list
It would be nice to include the Wrapped Ether prices (equivalent to ETH's price) in the token transfers layout. Currently there is no price for Wrapped Ether:
image

### PR DESCRIPTION
**Pull request by sealer3**
Fixes #605 by mapping the Wrapped Ether address to Chainlink's "Ether" address

### CODE REVIEW

**Comment by sealer3** [comment]
@wmitsuda Can we revisit this? Not being able to see wrapped ETH prices in USD is a little frustrating.

**Comment by wmitsuda** [comment]
let's do it, rebase plz.

**Comment by sealer3** [comment]
Done. Here is an example:
image

(Any Uniswap trade that converts between ETH and WETH will have equivalent ETH/WETH amounts.)

**Review by wmitsuda — APPROVED** [review]
good!

**Pull request merged**
