### PR TITLE
Show contract attributes on the address Overview tab

### LINKED ISSUE #1385: UI improvements for the read contract proxy support
This is a follow up of #1251 with some UI polishing:

- Rename "Contract as Proxy" tab to "Logic Contract".
- If the contract is detected as a proxy, let's add two new entries to the "Overview" tab, just  below "Contract Creator":
  - "Proxy type": in this case it's be "ERC1167 minimal proxy". There will be other when we implement it in the node side.
  - "Logic contract": the logic contract address with all UI decorations as always.

### PR DESCRIPTION
**Pull request by sealer3**
Also renames "Contract as Proxy" to "Logic Contract".

Closes #1385

### CODE REVIEW

**Comment by sealer3** [comment]
Example:
image

**Review by wmitsuda — CHANGES_REQUESTED** [review]
I still prefer "Logic contract" as the description instead of "Proxy logic address", and it matches the naming of the tab (which act more as a shortcut to the contract source code).

Can we also make a totally unrelated improvement here? I just realized that because the balance row is also lazy loaded, now it is very noticeable the it "jumps", can we apply some pending to the balance value itself and let the row always be showing so it doesn't jump?

**Comment by sealer3** [comment]
Sure. I've changed the title to "Logic contract", though I wonder if people would have a hard time making the connection that it's part of the proxy.

And this is what the balance looks like while it's pending:
image

You might notice that the PendingItem component I used is slightly darker than the PendingResults below it.

**Review by wmitsuda — APPROVED** [review]

**Comment by wmitsuda** [comment]
lgtm

**Pull request merged**
