### PR TITLE
Updated Kleros token list

### PR DESCRIPTION
**Pull request by reyei**
- Updated the Kleros token list up to February 2nd, 2024
- Bump Prettier to latest version for the file

Note to admin: I'm open to doing the same for Kleros' community vetted address tags as well as CDNs. I'll however need some technical assistance with completing this. This can help with providing relevant metadata associated with addresses. @wmitsuda open to having a conversation about this?

### CODE REVIEW

**Comment by wmitsuda** [comment]
hi, thanks for the PR!

the prettier was already updated in `develop` branch, so could you remove that update and rebase plz?

also, could you point me where did you take the updated list for verification purposes? because it has a few differences from the one I downloaded right now, but it maybe just that it was updated since the PR was opened.

**Comment by wmitsuda** [comment]
for address tags, we still don't have a base structure inside Otterscan to support that, but anyway once having that in place, having an initial curated database would be helpful, and I'm open to discuss it.

**Comment by reyei** [comment]
The token list is pretty much updated everyday. We could potentially handle updating the list for you on a bi-monthly basis if that works for you. Same for the address tags when you have the framework in place. We could schedule in a conversation for next week if you'd like. Feel free to book in a time on my calendly: https://calendly.com/princeireye

**Comment by wmitsuda** [comment]
@reyei what is your affiliation with the Kleros project?

sorry for the question, but since your github account seems very new, I need to ask for security reasons.

**Comment by reyei** [comment]
Yeah I can completely understand that @wmitsuda. I'm a business development analyst intern at Kleros. Here's my LinkedIn if that helps https://www.linkedin.com/in/princeireye/

**Comment by wmitsuda** [comment]
thanks, we'll merge it.

can you just adjust a prettier styling error the CI signaled, pls?

**Comment by reyei** [comment]
Hi @wmitsuda, just following up on our previous conversations regarding a curated database. I wanted to check if you are still open to discussing this further.

I understand the base structure has not been completely set up yet on your end. No worries if you're still working on that. When you have more updates on the progress and capabilities on your side, I would appreciate connecting for another conversation. Feel free to suggest some times that work for you. Alternatively, you can book a time on https://calendly.com/princeireye . Thanks again and look forward to hearing from you.

**Comment by gmkung** [comment]
Just caught up with this thread. @wmitsuda I'm the Integrations Lead at Kleros and I'm confirming that Prince is part of the team!

**Comment by wmitsuda** [comment]
> Hi @wmitsuda, just following up on our previous conversations regarding a curated database. I wanted to check if you are still open to discussing this further.
> 
> I understand the base structure has not been completely set up yet on your end. No worries if you're still working on that. When you have more updates on the progress and capabilities on your side, I would appreciate connecting for another conversation. Feel free to suggest some times that work for you. Alternatively, you can book a time on https://calendly.com/princeireye . Thanks again and look forward to hearing from you.

sure, lets try some time this week or after ethdenver (even better if you are attending it, let me know)

**Pull request merged**
