### PR TITLE
Add data loader to address page

### PR DESCRIPTION
**Pull request by sealer3**
For #2388

### CODE REVIEW

**Comment by sealer3** [comment]
This is a first attempt at getting AddressMainPage to use a data loader. It fetches whether the address has code right when navigation begins.

@wmitsuda This change causes the whole page to flash when you change tabs. Do you have any idea why this happens?

**Comment by sealer3** [comment]
The reason I saw the tabs flashing is that the address tabs are now lazy-loaded. This greatly reduces the Address page size. Previously it was the largest page code to load at 1,095 kB, and now it is 39.56 kB. Nonetheless we might want to consider finding a way to load some of the tab code early.

**Comment by sealer3** [comment]
Sadly there is still a full content shift when the address changes. I'm not sure why, since the loader's return values are completely deferred now.

**Comment by wmitsuda** [comment]
> The reason I saw the tabs flashing is that the address tabs are now lazy-loaded. This greatly reduces the Address page size. Previously it was the largest page code to load at 1,095 kB, and now it is 39.56 kB. Nonetheless we might want to consider finding a way to load some of the tab code early.

do you mean, the code imports? I think would be ok to not-lazy load some of them or apply some load tricks (I have some in mind if you want to go that way).

**Comment by sealer3** [comment]
Yes, that's what I meant, the code for the tabs are lazy-loaded. I think it's great that the address page from a cold start loads faster but think it would be best if all the tab code eventually loads on its own. If that doesn't seem possible we can just make the Contract tab and any other frequently used ones non-lazy.

I would really like to hear if you have any ideas for why there is a full content shift when the address changes. I haven't yet figured it out yet.

**Comment by wmitsuda** [comment]
> Yes, that's what I meant, the code for the tabs are lazy-loaded. I think it's great that the address page from a cold start loads faster but think it would be best if all the tab code eventually loads on its own. If that doesn't seem possible we can just make the Contract tab and any other frequently used ones non-lazy, as you said.

I think you can try the technique described here (strategy 3, lazy load + trigger on tab hover): https://mikeguoynes.medium.com/the-ultimate-guide-to-react-lazy-loading-4cacd8bd3cf0

> 
> I would really like to hear if you have any ideas for why there is a full content shift when the address changes. I haven't yet figured it out yet.

by address change you mean it flashes only at the first tab change, right? probably because the lazy tab suspends, after that I can't see any flashes while switching tabs

**Comment by sealer3** [comment]
No, I mean when you click different addresses in the transaction results, there is a flash every time on my end.

**Comment by wmitsuda** [comment]
ah, I see... I suspect all the chain of useEffects while rendering the AddressMainPage is leading to the flash on rerendering, maybe the checksummedAddress calculation.

I think moving those useEffects to loaders will eliminate most of those flashes, or at least cause the Suspends on more narrow parts of the page.

**Comment by wmitsuda** [comment]
the code for useAddressOrENS is really ugly :(

what if we decouple the checksummed address fixer from it, so it does not block the rendering of the page, and the calculation of an eventual reverse ENS name can be progressively rendered?

**Comment by wmitsuda** [comment]
(those are my guesses looking quickly at the code, I may be guessing wrong)

**Comment by sealer3** [comment]
After stubbing it out, useAddressOrENS doesn't seem to be the cause. What I've noticed is that immediately (t = 0ms) after clicking a new address, useContractCreator and useTransactionCount from AddressTransactionResults are fired, using the old address. This happens also on a production build. I will keep investigating.

**Comment by sealer3** [comment]
`useLoaderData` is the culprit of the re-renders. Apparently it is a common complaint that the expected behavior is to re-render like this: https://github.com/remix-run/react-router/issues/10756 https://github.com/remix-run/react-router/issues/11134 https://github.com/remix-run/react-router/issues/11477

The solution according to the maintainers is to speed up renders:

> This is expected behavior. When you navigate, React Router updates useNavigation().state from idle to loading and remains on the current page while the loaders run for the next page. This causes the current page to re-render so that it can show any pending/optimistic UI based on useNavigation().
> 
> Re-renders are at the heart of React and are usually not an issue unless you have expensive/slow components, and you can optimize them individually if they are problematic: https://kentcdodds.com/blog/fix-the-slow-render-before-you-fix-the-re-render

There is some discussion of how to get around a re-render (by **not** using defer) here: https://github.com/remix-run/react-router/issues/10816

**Comment by sealer3** [comment]
Rerenders are not the root cause of the issue. Increasing the latency of network requests to the Erigon RPC server, which is used by the data loader, increases the length of the "flash" during which the entire AddressMainPage isn't shown. This happens regardless of whether we use `defer`.

**Comment by wmitsuda** [comment]
So, it is an "expected" flashing because it is loading new data? 

Maybe we can minimize that effect by using something like useDeferredData to keep rendering the old data until the new one is available?

**Comment by wmitsuda** [comment]
I guess maybe the previous code didn't have the flashing because we are somehow (I don't remember) already rendering the old data until it is replaced by the new, avoiding the flashing.

**Comment by sealer3** [comment]
Wrapping `useDeferredValue` around `useLoaderData` seems to work!

**Review by wmitsuda — APPROVED** [review]

**Pull request merged**
